#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        4
bspc config window_gap          12
bspc config top_padding 	    26

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config single_monocle      true

#bspc config click_to_focus       true
bspc config focus_follows_pointer true

bspc config focused_border_color "#928374"
bspc config normal_border_color  "#504945"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Set background
feh --bg-center ~/Pictures/drawn-wallpaper-nature-3.jpg

# Start compton
compton -b

# Start polybar
$HOME/.config/polybar/launch.sh
