#! /bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width        4
bspc config window_gap          12
bspc config top_padding 	    26

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config single_monocle      true

#bspc config click_to_focus       true
bspc config focus_follows_pointer true

bspc config focused_border_color "#928374"
bspc config normal_border_color  "#504945"

bspc rule -a Gimp state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a Whatsie desktop='0'
bspc rule -a Caprine desktop='0'
bspc rule -a 'Messenger for Desktop' desktop='0'
bspc rule -a Skype desktop='0'

# Set background
feh --bg-center ~/Pictures/drawn-wallpaper-nature-3.jpg

# Start compton
compton -b

# Start polybar
$HOME/.config/polybar/launch.sh

# QT5 program themes
export QT_QPA_PLATFORMTHEME=gtk2
